name: 'GUI Screenshot'
author: 'Boredom101'
description: 'Takes a screenshot of a graphical program'
inputs:
  rows:
    description: 'Rows of text the terminal should have'
    required: true
  cols:
    description: 'Columns of text the terminal should have'
  path:
    description: 'Path to save image at'
    required: true
  sleep:
    description: 'How long the command needs to get to the desired state'
    required: true
  command:
    description: 'A path to the command to run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rows }}
    - ${{ inputs.cols }}
    - ${{ inputs.path }}
    - ${{ inputs.sleep }}
    - ${{ inputs.command }}
